### ISSUE TITLE
nrpe-ng can't regulary stop under Debian 10

### ISSUE THREAD

**Issue by TeTeHacko** [bootc/nrpe-ng#3]
```
Feb 27 09:03:08 hostname systemd[1]: Started The next generation Nagios Remote Plugin Executor.
Feb 27 09:03:13 hostname systemd[1]: Stopping The next generation Nagios Remote Plugin Executor...
Feb 27 09:03:13 hostname nrpe-ng[1761987]: received SIGTERM, shutting down...
Feb 27 09:03:13 hostname nrpe-ng[1761987]: Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fb3e4b23f28>, <Future finished exception=AttributeError("'AsyncIOMainLoop' object has no attribute '_callb>
                                                 Traceback (most recent call last):
                                                   File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 758, in _run_callback
                                                     ret = callback()
                                                   File "/usr/lib/python3/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
                                                     return fn(*args, **kwargs)
                                                   File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 779, in _discard_future_result
                                                     future.result()
                                                   File "/usr/lib/python3/dist-packages/tornado/gen.py", line 326, in wrapper
                                                     yielded = next(result)
                                                   File "/usr/lib/python3/dist-packages/nrpe_ng/server/server.py", line 182, in sigterm_callback
                                                     if not io_loop.callbacks and not io_loop._timeouts:
                                                 AttributeError: 'AsyncIOMainLoop' object has no attribute '_callbacks'
Feb 27 09:04:43 hostname systemd[1]: nrpe-ng.service: State 'stop-sigterm' timed out. Killing.
Feb 27 09:04:43 hostname systemd[1]: nrpe-ng.service: Killing process 1761987 (nrpe-ng) with signal SIGKILL.
Feb 27 09:04:43 hostname systemd[1]: nrpe-ng.service: Main process exited, code=killed, status=9/KILL
Feb 27 09:04:43 hostname systemd[1]: nrpe-ng.service: Failed with result 'timeout'.
Feb 27 09:04:43 hostname systemd[1]: Stopped The next generation Nagios Remote Plugin Executor.

```

**Comment by TeTeHacko** [comment]
quick and dirty workaround:
add line to `/lib/systemd/system/nrpe-ng.service` in `[Service]` section:
```KillSignal=9```

**Comment by TeTeHacko** [comment]
quick and dirty workaround:
add line to `/lib/systemd/system/nrpe-ng.service` in `[Service]` section:
```KillSignal=9```

**Comment by infraweavers** [comment]
We've just hit this problem as well, the presentation is that it takes about 90 seconds to restart the service for configuration changes. Essentially rendering nrpe-ng useless :( However working around it by changing the unit definition works fine. 

Is there any way to get this patched into the releases for Debian 11? @bootc

**Comment by russellvt** [comment]
Added this issue in my fork: russellvt/nrpe-ng#2 ... will see if I can reproduce, etc.

Feel free to come over to my fork and comment.
